// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HttpRpcProtos.proto

package mobi.suishi.rpc;

public final class HttpRpcProtos {
  private HttpRpcProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code rpc.ErrorReason}
   *
   * <pre>
   * Possible error reasons
   * The server-side errors are returned in the response from the server.
   * The client-side errors are returned by the client-side code when it doesn't 
   * have a response from the server.
   * </pre>
   */
  public enum ErrorReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BAD_REQUEST_DATA = 0;</code>
     *
     * <pre>
     * Server-side errors
     * </pre>
     */
    BAD_REQUEST_DATA(0, 0),
    /**
     * <code>BAD_REQUEST_PROTO = 1;</code>
     *
     * <pre>
     * Server received bad request proto
     * </pre>
     */
    BAD_REQUEST_PROTO(1, 1),
    /**
     * <code>SERVICE_NOT_FOUND = 2;</code>
     *
     * <pre>
     * Service not found on server
     * </pre>
     */
    SERVICE_NOT_FOUND(2, 2),
    /**
     * <code>METHOD_NOT_FOUND = 3;</code>
     *
     * <pre>
     * Method not found on server
     * </pre>
     */
    METHOD_NOT_FOUND(3, 3),
    /**
     * <code>RPC_ERROR = 4;</code>
     *
     * <pre>
     * Rpc threw exception on server
     * </pre>
     */
    RPC_ERROR(4, 4),
    /**
     * <code>RPC_FAILED = 5;</code>
     *
     * <pre>
     * Rpc failed on server
     * </pre>
     */
    RPC_FAILED(5, 5),
    /**
     * <code>INVALID_REQUEST_PROTO = 6;</code>
     *
     * <pre>
     * Client-side errors (these are returned by the client-side code)
     * </pre>
     */
    INVALID_REQUEST_PROTO(6, 6),
    /**
     * <code>BAD_RESPONSE_PROTO = 7;</code>
     *
     * <pre>
     * Server returned a bad response proto
     * </pre>
     */
    BAD_RESPONSE_PROTO(7, 7),
    /**
     * <code>UNKNOWN_HOST = 8;</code>
     *
     * <pre>
     * Could not find supplied host
     * </pre>
     */
    UNKNOWN_HOST(8, 8),
    /**
     * <code>IO_ERROR = 9;</code>
     *
     * <pre>
     * I/O error while communicating with server
     * </pre>
     */
    IO_ERROR(9, 9),
    ;

    /**
     * <code>BAD_REQUEST_DATA = 0;</code>
     *
     * <pre>
     * Server-side errors
     * </pre>
     */
    public static final int BAD_REQUEST_DATA_VALUE = 0;
    /**
     * <code>BAD_REQUEST_PROTO = 1;</code>
     *
     * <pre>
     * Server received bad request proto
     * </pre>
     */
    public static final int BAD_REQUEST_PROTO_VALUE = 1;
    /**
     * <code>SERVICE_NOT_FOUND = 2;</code>
     *
     * <pre>
     * Service not found on server
     * </pre>
     */
    public static final int SERVICE_NOT_FOUND_VALUE = 2;
    /**
     * <code>METHOD_NOT_FOUND = 3;</code>
     *
     * <pre>
     * Method not found on server
     * </pre>
     */
    public static final int METHOD_NOT_FOUND_VALUE = 3;
    /**
     * <code>RPC_ERROR = 4;</code>
     *
     * <pre>
     * Rpc threw exception on server
     * </pre>
     */
    public static final int RPC_ERROR_VALUE = 4;
    /**
     * <code>RPC_FAILED = 5;</code>
     *
     * <pre>
     * Rpc failed on server
     * </pre>
     */
    public static final int RPC_FAILED_VALUE = 5;
    /**
     * <code>INVALID_REQUEST_PROTO = 6;</code>
     *
     * <pre>
     * Client-side errors (these are returned by the client-side code)
     * </pre>
     */
    public static final int INVALID_REQUEST_PROTO_VALUE = 6;
    /**
     * <code>BAD_RESPONSE_PROTO = 7;</code>
     *
     * <pre>
     * Server returned a bad response proto
     * </pre>
     */
    public static final int BAD_RESPONSE_PROTO_VALUE = 7;
    /**
     * <code>UNKNOWN_HOST = 8;</code>
     *
     * <pre>
     * Could not find supplied host
     * </pre>
     */
    public static final int UNKNOWN_HOST_VALUE = 8;
    /**
     * <code>IO_ERROR = 9;</code>
     *
     * <pre>
     * I/O error while communicating with server
     * </pre>
     */
    public static final int IO_ERROR_VALUE = 9;


    public final int getNumber() { return value; }

    public static ErrorReason valueOf(int value) {
      switch (value) {
        case 0: return BAD_REQUEST_DATA;
        case 1: return BAD_REQUEST_PROTO;
        case 2: return SERVICE_NOT_FOUND;
        case 3: return METHOD_NOT_FOUND;
        case 4: return RPC_ERROR;
        case 5: return RPC_FAILED;
        case 6: return INVALID_REQUEST_PROTO;
        case 7: return BAD_RESPONSE_PROTO;
        case 8: return UNKNOWN_HOST;
        case 9: return IO_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorReason>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorReason>() {
            public ErrorReason findValueByNumber(int number) {
              return ErrorReason.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return mobi.suishi.rpc.HttpRpcProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorReason[] VALUES = values();

    public static ErrorReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorReason(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rpc.ErrorReason)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string service_name = 1;</code>
     *
     * <pre>
     * RPC service full name
     * </pre>
     */
    boolean hasServiceName();
    /**
     * <code>required string service_name = 1;</code>
     *
     * <pre>
     * RPC service full name
     * </pre>
     */
    java.lang.String getServiceName();
    /**
     * <code>required string service_name = 1;</code>
     *
     * <pre>
     * RPC service full name
     * </pre>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     * RPC method name
     * </pre>
     */
    boolean hasMethodName();
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     * RPC method name
     * </pre>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     * RPC method name
     * </pre>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>optional int32 request_flag = 3;</code>
     *
     * <pre>
     * RPC request flag
     * </pre>
     */
    boolean hasRequestFlag();
    /**
     * <code>optional int32 request_flag = 3;</code>
     *
     * <pre>
     * RPC request flag
     * </pre>
     */
    int getRequestFlag();

    /**
     * <code>required bytes request_proto = 4;</code>
     *
     * <pre>
     * RPC request proto
     * </pre>
     */
    boolean hasRequestProto();
    /**
     * <code>required bytes request_proto = 4;</code>
     *
     * <pre>
     * RPC request proto
     * </pre>
     */
    com.google.protobuf.ByteString getRequestProto();

    /**
     * <code>optional int32 client_version = 5;</code>
     *
     * <pre>
     *client version
     * </pre>
     */
    boolean hasClientVersion();
    /**
     * <code>optional int32 client_version = 5;</code>
     *
     * <pre>
     *client version
     * </pre>
     */
    int getClientVersion();

    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     *client package name
     * </pre>
     */
    boolean hasPackageName();
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     *client package name
     * </pre>
     */
    java.lang.String getPackageName();
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     *client package name
     * </pre>
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();

    /**
     * <code>optional string channel = 7;</code>
     *
     * <pre>
     *client channel
     * </pre>
     */
    boolean hasChannel();
    /**
     * <code>optional string channel = 7;</code>
     *
     * <pre>
     *client channel
     * </pre>
     */
    java.lang.String getChannel();
    /**
     * <code>optional string channel = 7;</code>
     *
     * <pre>
     *client channel
     * </pre>
     */
    com.google.protobuf.ByteString
        getChannelBytes();
  }
  /**
   * Protobuf type {@code rpc.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serviceName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              methodName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              requestFlag_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              requestProto_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              clientVersion_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              packageName_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              channel_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mobi.suishi.rpc.HttpRpcProtos.Request.class, mobi.suishi.rpc.HttpRpcProtos.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVICE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object serviceName_;
    /**
     * <code>required string service_name = 1;</code>
     *
     * <pre>
     * RPC service full name
     * </pre>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string service_name = 1;</code>
     *
     * <pre>
     * RPC service full name
     * </pre>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string service_name = 1;</code>
     *
     * <pre>
     * RPC service full name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     * RPC method name
     * </pre>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     * RPC method name
     * </pre>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     * RPC method name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_FLAG_FIELD_NUMBER = 3;
    private int requestFlag_;
    /**
     * <code>optional int32 request_flag = 3;</code>
     *
     * <pre>
     * RPC request flag
     * </pre>
     */
    public boolean hasRequestFlag() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 request_flag = 3;</code>
     *
     * <pre>
     * RPC request flag
     * </pre>
     */
    public int getRequestFlag() {
      return requestFlag_;
    }

    public static final int REQUEST_PROTO_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString requestProto_;
    /**
     * <code>required bytes request_proto = 4;</code>
     *
     * <pre>
     * RPC request proto
     * </pre>
     */
    public boolean hasRequestProto() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes request_proto = 4;</code>
     *
     * <pre>
     * RPC request proto
     * </pre>
     */
    public com.google.protobuf.ByteString getRequestProto() {
      return requestProto_;
    }

    public static final int CLIENT_VERSION_FIELD_NUMBER = 5;
    private int clientVersion_;
    /**
     * <code>optional int32 client_version = 5;</code>
     *
     * <pre>
     *client version
     * </pre>
     */
    public boolean hasClientVersion() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 client_version = 5;</code>
     *
     * <pre>
     *client version
     * </pre>
     */
    public int getClientVersion() {
      return clientVersion_;
    }

    public static final int PACKAGE_NAME_FIELD_NUMBER = 6;
    private java.lang.Object packageName_;
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     *client package name
     * </pre>
     */
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     *client package name
     * </pre>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     *client package name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_FIELD_NUMBER = 7;
    private java.lang.Object channel_;
    /**
     * <code>optional string channel = 7;</code>
     *
     * <pre>
     *client channel
     * </pre>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string channel = 7;</code>
     *
     * <pre>
     *client channel
     * </pre>
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string channel = 7;</code>
     *
     * <pre>
     *client channel
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serviceName_ = "";
      methodName_ = "";
      requestFlag_ = 0;
      requestProto_ = com.google.protobuf.ByteString.EMPTY;
      clientVersion_ = 0;
      packageName_ = "";
      channel_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServiceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestProto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, requestFlag_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, requestProto_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, clientVersion_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPackageNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getChannelBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, requestFlag_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, requestProto_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, clientVersion_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPackageNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getChannelBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mobi.suishi.rpc.HttpRpcProtos.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mobi.suishi.rpc.HttpRpcProtos.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.Request)
        mobi.suishi.rpc.HttpRpcProtos.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mobi.suishi.rpc.HttpRpcProtos.Request.class, mobi.suishi.rpc.HttpRpcProtos.Request.Builder.class);
      }

      // Construct using mobi.suishi.rpc.HttpRpcProtos.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        requestProto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        clientVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        packageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        channel_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Request_descriptor;
      }

      public mobi.suishi.rpc.HttpRpcProtos.Request getDefaultInstanceForType() {
        return mobi.suishi.rpc.HttpRpcProtos.Request.getDefaultInstance();
      }

      public mobi.suishi.rpc.HttpRpcProtos.Request build() {
        mobi.suishi.rpc.HttpRpcProtos.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mobi.suishi.rpc.HttpRpcProtos.Request buildPartial() {
        mobi.suishi.rpc.HttpRpcProtos.Request result = new mobi.suishi.rpc.HttpRpcProtos.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestFlag_ = requestFlag_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.requestProto_ = requestProto_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.clientVersion_ = clientVersion_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.packageName_ = packageName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.channel_ = channel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mobi.suishi.rpc.HttpRpcProtos.Request) {
          return mergeFrom((mobi.suishi.rpc.HttpRpcProtos.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mobi.suishi.rpc.HttpRpcProtos.Request other) {
        if (other == mobi.suishi.rpc.HttpRpcProtos.Request.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000001;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasRequestFlag()) {
          setRequestFlag(other.getRequestFlag());
        }
        if (other.hasRequestProto()) {
          setRequestProto(other.getRequestProto());
        }
        if (other.hasClientVersion()) {
          setClientVersion(other.getClientVersion());
        }
        if (other.hasPackageName()) {
          bitField0_ |= 0x00000020;
          packageName_ = other.packageName_;
          onChanged();
        }
        if (other.hasChannel()) {
          bitField0_ |= 0x00000040;
          channel_ = other.channel_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceName()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        if (!hasRequestProto()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mobi.suishi.rpc.HttpRpcProtos.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mobi.suishi.rpc.HttpRpcProtos.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serviceName_ = "";
      /**
       * <code>required string service_name = 1;</code>
       *
       * <pre>
       * RPC service full name
       * </pre>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string service_name = 1;</code>
       *
       * <pre>
       * RPC service full name
       * </pre>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string service_name = 1;</code>
       *
       * <pre>
       * RPC service full name
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string service_name = 1;</code>
       *
       * <pre>
       * RPC service full name
       * </pre>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string service_name = 1;</code>
       *
       * <pre>
       * RPC service full name
       * </pre>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string service_name = 1;</code>
       *
       * <pre>
       * RPC service full name
       * </pre>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       * RPC method name
       * </pre>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       * RPC method name
       * </pre>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            methodName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       * RPC method name
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       * RPC method name
       * </pre>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       * RPC method name
       * </pre>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       * RPC method name
       * </pre>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      private int requestFlag_ ;
      /**
       * <code>optional int32 request_flag = 3;</code>
       *
       * <pre>
       * RPC request flag
       * </pre>
       */
      public boolean hasRequestFlag() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 request_flag = 3;</code>
       *
       * <pre>
       * RPC request flag
       * </pre>
       */
      public int getRequestFlag() {
        return requestFlag_;
      }
      /**
       * <code>optional int32 request_flag = 3;</code>
       *
       * <pre>
       * RPC request flag
       * </pre>
       */
      public Builder setRequestFlag(int value) {
        bitField0_ |= 0x00000004;
        requestFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 request_flag = 3;</code>
       *
       * <pre>
       * RPC request flag
       * </pre>
       */
      public Builder clearRequestFlag() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestFlag_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestProto_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes request_proto = 4;</code>
       *
       * <pre>
       * RPC request proto
       * </pre>
       */
      public boolean hasRequestProto() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes request_proto = 4;</code>
       *
       * <pre>
       * RPC request proto
       * </pre>
       */
      public com.google.protobuf.ByteString getRequestProto() {
        return requestProto_;
      }
      /**
       * <code>required bytes request_proto = 4;</code>
       *
       * <pre>
       * RPC request proto
       * </pre>
       */
      public Builder setRequestProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        requestProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes request_proto = 4;</code>
       *
       * <pre>
       * RPC request proto
       * </pre>
       */
      public Builder clearRequestProto() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestProto_ = getDefaultInstance().getRequestProto();
        onChanged();
        return this;
      }

      private int clientVersion_ ;
      /**
       * <code>optional int32 client_version = 5;</code>
       *
       * <pre>
       *client version
       * </pre>
       */
      public boolean hasClientVersion() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 client_version = 5;</code>
       *
       * <pre>
       *client version
       * </pre>
       */
      public int getClientVersion() {
        return clientVersion_;
      }
      /**
       * <code>optional int32 client_version = 5;</code>
       *
       * <pre>
       *client version
       * </pre>
       */
      public Builder setClientVersion(int value) {
        bitField0_ |= 0x00000010;
        clientVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 client_version = 5;</code>
       *
       * <pre>
       *client version
       * </pre>
       */
      public Builder clearClientVersion() {
        bitField0_ = (bitField0_ & ~0x00000010);
        clientVersion_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object packageName_ = "";
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       *client package name
       * </pre>
       */
      public boolean hasPackageName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       *client package name
       * </pre>
       */
      public java.lang.String getPackageName() {
        java.lang.Object ref = packageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packageName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       *client package name
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        java.lang.Object ref = packageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       *client package name
       * </pre>
       */
      public Builder setPackageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        packageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       *client package name
       * </pre>
       */
      public Builder clearPackageName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        packageName_ = getDefaultInstance().getPackageName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       *client package name
       * </pre>
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        packageName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object channel_ = "";
      /**
       * <code>optional string channel = 7;</code>
       *
       * <pre>
       *client channel
       * </pre>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string channel = 7;</code>
       *
       * <pre>
       *client channel
       * </pre>
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channel = 7;</code>
       *
       * <pre>
       *client channel
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channel = 7;</code>
       *
       * <pre>
       *client channel
       * </pre>
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 7;</code>
       *
       * <pre>
       *client channel
       * </pre>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 7;</code>
       *
       * <pre>
       *client channel
       * </pre>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        channel_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rpc.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rpc.Request)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 response_flag = 1;</code>
     *
     * <pre>
     *RPC response flag
     * </pre>
     */
    boolean hasResponseFlag();
    /**
     * <code>optional int32 response_flag = 1;</code>
     *
     * <pre>
     *RPC response flag
     * </pre>
     */
    int getResponseFlag();

    /**
     * <code>optional bytes response_proto = 2;</code>
     *
     * <pre>
     * RPC response proto
     * </pre>
     */
    boolean hasResponseProto();
    /**
     * <code>optional bytes response_proto = 2;</code>
     *
     * <pre>
     * RPC response proto
     * </pre>
     */
    com.google.protobuf.ByteString getResponseProto();

    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     * Error, if any
     * </pre>
     */
    boolean hasError();
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     * Error, if any
     * </pre>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     * Error, if any
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    /**
     * <code>optional bool callback = 4 [default = false];</code>
     *
     * <pre>
     * Was callback invoked
     * </pre>
     */
    boolean hasCallback();
    /**
     * <code>optional bool callback = 4 [default = false];</code>
     *
     * <pre>
     * Was callback invoked
     * </pre>
     */
    boolean getCallback();

    /**
     * <code>optional .rpc.ErrorReason error_reason = 5;</code>
     *
     * <pre>
     * Error Reason
     * </pre>
     */
    boolean hasErrorReason();
    /**
     * <code>optional .rpc.ErrorReason error_reason = 5;</code>
     *
     * <pre>
     * Error Reason
     * </pre>
     */
    mobi.suishi.rpc.HttpRpcProtos.ErrorReason getErrorReason();
  }
  /**
   * Protobuf type {@code rpc.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              responseFlag_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              responseProto_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              error_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              callback_ = input.readBool();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              mobi.suishi.rpc.HttpRpcProtos.ErrorReason value = mobi.suishi.rpc.HttpRpcProtos.ErrorReason.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                errorReason_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mobi.suishi.rpc.HttpRpcProtos.Response.class, mobi.suishi.rpc.HttpRpcProtos.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESPONSE_FLAG_FIELD_NUMBER = 1;
    private int responseFlag_;
    /**
     * <code>optional int32 response_flag = 1;</code>
     *
     * <pre>
     *RPC response flag
     * </pre>
     */
    public boolean hasResponseFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 response_flag = 1;</code>
     *
     * <pre>
     *RPC response flag
     * </pre>
     */
    public int getResponseFlag() {
      return responseFlag_;
    }

    public static final int RESPONSE_PROTO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString responseProto_;
    /**
     * <code>optional bytes response_proto = 2;</code>
     *
     * <pre>
     * RPC response proto
     * </pre>
     */
    public boolean hasResponseProto() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes response_proto = 2;</code>
     *
     * <pre>
     * RPC response proto
     * </pre>
     */
    public com.google.protobuf.ByteString getResponseProto() {
      return responseProto_;
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     * Error, if any
     * </pre>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     * Error, if any
     * </pre>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     * Error, if any
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CALLBACK_FIELD_NUMBER = 4;
    private boolean callback_;
    /**
     * <code>optional bool callback = 4 [default = false];</code>
     *
     * <pre>
     * Was callback invoked
     * </pre>
     */
    public boolean hasCallback() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool callback = 4 [default = false];</code>
     *
     * <pre>
     * Was callback invoked
     * </pre>
     */
    public boolean getCallback() {
      return callback_;
    }

    public static final int ERROR_REASON_FIELD_NUMBER = 5;
    private mobi.suishi.rpc.HttpRpcProtos.ErrorReason errorReason_;
    /**
     * <code>optional .rpc.ErrorReason error_reason = 5;</code>
     *
     * <pre>
     * Error Reason
     * </pre>
     */
    public boolean hasErrorReason() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .rpc.ErrorReason error_reason = 5;</code>
     *
     * <pre>
     * Error Reason
     * </pre>
     */
    public mobi.suishi.rpc.HttpRpcProtos.ErrorReason getErrorReason() {
      return errorReason_;
    }

    private void initFields() {
      responseFlag_ = 0;
      responseProto_ = com.google.protobuf.ByteString.EMPTY;
      error_ = "";
      callback_ = false;
      errorReason_ = mobi.suishi.rpc.HttpRpcProtos.ErrorReason.BAD_REQUEST_DATA;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, responseFlag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, responseProto_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, callback_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, errorReason_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseFlag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, responseProto_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, callback_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, errorReason_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mobi.suishi.rpc.HttpRpcProtos.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mobi.suishi.rpc.HttpRpcProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mobi.suishi.rpc.HttpRpcProtos.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.Response)
        mobi.suishi.rpc.HttpRpcProtos.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mobi.suishi.rpc.HttpRpcProtos.Response.class, mobi.suishi.rpc.HttpRpcProtos.Response.Builder.class);
      }

      // Construct using mobi.suishi.rpc.HttpRpcProtos.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        responseFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseProto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        callback_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        errorReason_ = mobi.suishi.rpc.HttpRpcProtos.ErrorReason.BAD_REQUEST_DATA;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mobi.suishi.rpc.HttpRpcProtos.internal_static_rpc_Response_descriptor;
      }

      public mobi.suishi.rpc.HttpRpcProtos.Response getDefaultInstanceForType() {
        return mobi.suishi.rpc.HttpRpcProtos.Response.getDefaultInstance();
      }

      public mobi.suishi.rpc.HttpRpcProtos.Response build() {
        mobi.suishi.rpc.HttpRpcProtos.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mobi.suishi.rpc.HttpRpcProtos.Response buildPartial() {
        mobi.suishi.rpc.HttpRpcProtos.Response result = new mobi.suishi.rpc.HttpRpcProtos.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseFlag_ = responseFlag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseProto_ = responseProto_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.callback_ = callback_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.errorReason_ = errorReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mobi.suishi.rpc.HttpRpcProtos.Response) {
          return mergeFrom((mobi.suishi.rpc.HttpRpcProtos.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mobi.suishi.rpc.HttpRpcProtos.Response other) {
        if (other == mobi.suishi.rpc.HttpRpcProtos.Response.getDefaultInstance()) return this;
        if (other.hasResponseFlag()) {
          setResponseFlag(other.getResponseFlag());
        }
        if (other.hasResponseProto()) {
          setResponseProto(other.getResponseProto());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000004;
          error_ = other.error_;
          onChanged();
        }
        if (other.hasCallback()) {
          setCallback(other.getCallback());
        }
        if (other.hasErrorReason()) {
          setErrorReason(other.getErrorReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mobi.suishi.rpc.HttpRpcProtos.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mobi.suishi.rpc.HttpRpcProtos.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int responseFlag_ ;
      /**
       * <code>optional int32 response_flag = 1;</code>
       *
       * <pre>
       *RPC response flag
       * </pre>
       */
      public boolean hasResponseFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 response_flag = 1;</code>
       *
       * <pre>
       *RPC response flag
       * </pre>
       */
      public int getResponseFlag() {
        return responseFlag_;
      }
      /**
       * <code>optional int32 response_flag = 1;</code>
       *
       * <pre>
       *RPC response flag
       * </pre>
       */
      public Builder setResponseFlag(int value) {
        bitField0_ |= 0x00000001;
        responseFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 response_flag = 1;</code>
       *
       * <pre>
       *RPC response flag
       * </pre>
       */
      public Builder clearResponseFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseFlag_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString responseProto_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response_proto = 2;</code>
       *
       * <pre>
       * RPC response proto
       * </pre>
       */
      public boolean hasResponseProto() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes response_proto = 2;</code>
       *
       * <pre>
       * RPC response proto
       * </pre>
       */
      public com.google.protobuf.ByteString getResponseProto() {
        return responseProto_;
      }
      /**
       * <code>optional bytes response_proto = 2;</code>
       *
       * <pre>
       * RPC response proto
       * </pre>
       */
      public Builder setResponseProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response_proto = 2;</code>
       *
       * <pre>
       * RPC response proto
       * </pre>
       */
      public Builder clearResponseProto() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseProto_ = getDefaultInstance().getResponseProto();
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       * Error, if any
       * </pre>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       * Error, if any
       * </pre>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            error_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       * Error, if any
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       * Error, if any
       * </pre>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       * Error, if any
       * </pre>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000004);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       * Error, if any
       * </pre>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }

      private boolean callback_ ;
      /**
       * <code>optional bool callback = 4 [default = false];</code>
       *
       * <pre>
       * Was callback invoked
       * </pre>
       */
      public boolean hasCallback() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool callback = 4 [default = false];</code>
       *
       * <pre>
       * Was callback invoked
       * </pre>
       */
      public boolean getCallback() {
        return callback_;
      }
      /**
       * <code>optional bool callback = 4 [default = false];</code>
       *
       * <pre>
       * Was callback invoked
       * </pre>
       */
      public Builder setCallback(boolean value) {
        bitField0_ |= 0x00000008;
        callback_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool callback = 4 [default = false];</code>
       *
       * <pre>
       * Was callback invoked
       * </pre>
       */
      public Builder clearCallback() {
        bitField0_ = (bitField0_ & ~0x00000008);
        callback_ = false;
        onChanged();
        return this;
      }

      private mobi.suishi.rpc.HttpRpcProtos.ErrorReason errorReason_ = mobi.suishi.rpc.HttpRpcProtos.ErrorReason.BAD_REQUEST_DATA;
      /**
       * <code>optional .rpc.ErrorReason error_reason = 5;</code>
       *
       * <pre>
       * Error Reason
       * </pre>
       */
      public boolean hasErrorReason() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .rpc.ErrorReason error_reason = 5;</code>
       *
       * <pre>
       * Error Reason
       * </pre>
       */
      public mobi.suishi.rpc.HttpRpcProtos.ErrorReason getErrorReason() {
        return errorReason_;
      }
      /**
       * <code>optional .rpc.ErrorReason error_reason = 5;</code>
       *
       * <pre>
       * Error Reason
       * </pre>
       */
      public Builder setErrorReason(mobi.suishi.rpc.HttpRpcProtos.ErrorReason value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        errorReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .rpc.ErrorReason error_reason = 5;</code>
       *
       * <pre>
       * Error Reason
       * </pre>
       */
      public Builder clearErrorReason() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errorReason_ = mobi.suishi.rpc.HttpRpcProtos.ErrorReason.BAD_REQUEST_DATA;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rpc.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rpc.Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023HttpRpcProtos.proto\022\003rpc\"\240\001\n\007Request\022\024" +
      "\n\014service_name\030\001 \002(\t\022\023\n\013method_name\030\002 \002(" +
      "\t\022\024\n\014request_flag\030\003 \001(\005\022\025\n\rrequest_proto" +
      "\030\004 \002(\014\022\026\n\016client_version\030\005 \001(\005\022\024\n\014packag" +
      "e_name\030\006 \001(\t\022\017\n\007channel\030\007 \001(\t\"\211\001\n\010Respon" +
      "se\022\025\n\rresponse_flag\030\001 \001(\005\022\026\n\016response_pr" +
      "oto\030\002 \001(\014\022\r\n\005error\030\003 \001(\t\022\027\n\010callback\030\004 \001" +
      "(\010:\005false\022&\n\014error_reason\030\005 \001(\0162\020.rpc.Er" +
      "rorReason*\331\001\n\013ErrorReason\022\024\n\020BAD_REQUEST" +
      "_DATA\020\000\022\025\n\021BAD_REQUEST_PROTO\020\001\022\025\n\021SERVIC",
      "E_NOT_FOUND\020\002\022\024\n\020METHOD_NOT_FOUND\020\003\022\r\n\tR" +
      "PC_ERROR\020\004\022\016\n\nRPC_FAILED\020\005\022\031\n\025INVALID_RE" +
      "QUEST_PROTO\020\006\022\026\n\022BAD_RESPONSE_PROTO\020\007\022\020\n" +
      "\014UNKNOWN_HOST\020\010\022\014\n\010IO_ERROR\020\tB \n\017mobi.su" +
      "ishi.rpcB\rHttpRpcProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rpc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_Request_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "RequestFlag", "RequestProto", "ClientVersion", "PackageName", "Channel", });
    internal_static_rpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_Response_descriptor,
        new java.lang.String[] { "ResponseFlag", "ResponseProto", "Error", "Callback", "ErrorReason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
